### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by ozgurovic** [unmannedlab/RELLIS-3D#17]
I have question regarding the folder structure. It is mentioned that 
"os1_cloud_node_kitti_bin/             -- directory containing ".bin" files with Velodyne point clouds. "
Are they ouster os1 or velodyne points. Do you provide .bin files for both velodyne and ouster?
Thanks in advance.

**Comment by maskjp** [comment]
Hi, @ozgurovic,

The bin files are for ouster os1 and have corresponding label files. We don't provide Velodyne bin files and corresponding labels. If you only want to get bin files for Velodyne, you can read the ROS bag and convert the point cloud to bin files.

Thanks!

**Comment by ozgurovic** [comment]
Thanks!
