### ISSUE TITLE
Color Image Labels

### ISSUE THREAD

**Issue by RawHeatG** [unmannedlab/RELLIS-3D#2]
Where can I find the **colored labels** for the camera images, they are there in the "Image with Annotation Examples" but for the whole dataset only label ids are there in the "Full Image Annotations"

**Comment by maskjp** [comment]
Hi,
Thanks for finding this problem!
I added the link on the readme page.
The following is the link:
https://drive.google.com/file/d/1HJl8Fi5nAjOr41DPUFmkeKWtDXhCZDke/view?usp=sharing

**Comment by RawHeatG** [comment]
Thanks a lot for the quick resolution @maskjp
