### ISSUE TITLE
Lidar to RGB Camera Calibration

### ISSUE THREAD

**Issue by ThomasR1337** [unmannedlab/RELLIS-3D#24]
I want to generate Depth maps from a Lidar source and the basler RGB Camera images.
Which Lidar source can be used? only one calibration file found: [https://drive.google.com/file/d/19EOqWS9fDUFp4nsBrMCa69xs9LgIlS2e/view](url)

**Comment by maskjp** [comment]
Hi, @ThomasR1337,

The calibration is for Ouster lidar and basler RGB Camera.

Hope this helps!

Best wishes!
