### ISSUE TITLE
OS1 Lidar max range setting

### ISSUE THREAD

**Issue by 78csai** [unmannedlab/RELLIS-3D#28]
Can you pls provide the used setting for the maximum range of the OS1.
According to the datasheet more settings are possible or does it mean the accuracy decreases with increasing range?
![image](https://user-images.githubusercontent.com/57364585/166169345-4d396565-f5c1-458e-915e-c9291126964c.png)

**Comment by maskjp** [comment]
Hi, @78csai,

I think the default maximum range of OS1 is 120m. We used the default setting. The performance depends on both range and Lambertian reflectivity. If 80% Lambertian reflectivity, the accuracy is high within 100 m. If you want high accuracy, you can only use data within 100 m. 

Hope this helps! 

Best wishes!

**Comment by 78csai** [comment]
thanks a lot!
