### ISSUE TITLE
How to generate the pose.txt for the labeling tool

### ISSUE THREAD

**Issue by SvenMuc** [unmannedlab/RELLIS-3D#7]
Hi,
really interesting approach and tools.

I'm currently trying to extend the dataset by own recordings. But I'm struggling with the pose.txt generation required by the KITTI labeling tool.

Do you have any recommendation how to generate the poses? In your paper you mentioned, that you used a SLAM approach.

Thanks
Sven

**Comment by maskjp** [comment]
Hi, @SvenMuc!

Thank you for your interest in RELLIS-3D. 

We used [Cartographer](https://github.com/cartographer-project/cartographer) to generate pose.txt. You can find the tool and configuration here: https://github.com/unmannedlab/cartographer. You can try this [script](https://github.com/unmannedlab/cartographer/blob/main/cart_config/output_pose) to run on a RELLIS-3D rosbag first. 

You can use any other SLAM or odometry estimation method to output the pose of your vehicle corresponding to each lidar scan. **LOAM** might also be a good choice: https://github.com/HKUST-Aerial-Robotics/A-LOAM

You can find more method here: http://www.cvlibs.net/datasets/kitti/eval_odometry.php

Hope this helps!

Best wishes!
